language: smalltalk
sudo: false

os:
  - linux

smalltalk:
  - Pharo-6.1

install:
  # Pillar installation
  - git clone https://github.com/pillar-markup/pillar.git -b dev-7 # Clone pillar
  - cd pillar && ./scripts/build.sh && cd ..                              # Run pillar build script. Pillar will be built in `pwd`/build!
  - . pillar/scripts/ci/ensure_latex.sh                                   # Install latex
  - ./pillar/scripts/ci/ensure_book_dependencies.sh                       # Install latex dependencies required by pillar
  
script:
  - ./pillar/build/pillar build pdf

deploy:
- provider: bintray
  file: .bintray.json
  on:
    repo: SquareBracketAssociates/DynamicWebDevelopmentWithSeaside
  skip_cleanup: true
  user: ducasse
  key:
    secure: mdhMJbjvS2d1Nrl/+hW71tNfL6vpCsiT7ZrhpKcpg+Odd6UbNMohyqHdEo7mgfGOF0KcaDHhz2I1wjRiGALoBd10hPYhJNF3SIIWzvB5s8SmrtvqYhoRmU+iliXHWoLCASiD9vYObDzqgRfB6+K9Vuh/tp2BReVffUezqaC5MTo=