language: pillar
sudo: false
addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-fonts-recommended
    - texlive-latex-extra
    - texlive-bibtex-extra
    - lmodern
    - latex-xcolor
    - libc6-i386

install:
  - ./download.sh

script:
  - ./compile.sh
